### ISSUE TITLE
The delete does not work

### ISSUE THREAD

**Issue by Ofer-Gal** [OfficeDev/TrainingContent#73] opened 2015-03-11 17:28 UTC
There is a "service.deleteCustomer " function in services.js but data-ng-click="deleteCustomer(customer.Id)" in home.html does not fire it.
I tried to make it : data-ng-click="wingtipCrmService.deleteCustomer(customer.Id)" 
but it did not work.
I don't have enough AngularJS experience to resolve it.

**Comment by jthake** [comment] 2015-03-11 20:45
I'm getting someone to take a look at this, thanks for raising it.

**Comment by TedPattison** [comment] 2015-03-12 13:01
Yes, this bug was my fault. The issue is that I missed adding the deleteCustomer function to the home controller. Here is the code before the bug fix.
app.controller('homeController',
    function ($scope, wingtipCrmService) {
         wingtipCrmService.getCustomers().success(function (data) {
           $scope.customers = data.d.results;
           }
        });
    }
);

Here is the code after the bug fix.
app.controller('homeController',
    function ($scope, wingtipCrmService) {
         wingtipCrmService.getCustomers().success(function (data) {
           $scope.customers = data.d.results;
           // add behavior function for view to call
           $scope.deleteCustomer = function (id) {
             wingtipCrmService.deleteCustomer(id).success(function (data) {
               $scope.$apply();
             });
           }
        });
    }
);

Once you add the deleteCustomers function to $scope, the Home view should be able to call it. I will now work with Jeremey to get the bug fix uploaded to the GitHub repository. Thanks for finding this.

**Comment by jthake** [comment] 2015-03-12 21:42
@TedPattison  has checked in fix.

**Closed by jthake** 2015-03-12 21:42 UTC
