### ISSUE TITLE
service.deleteCustomer is called but no remove an entry

### ISSUE THREAD

**Issue by Haystack0815** [OfficeDev/TrainingContent#114] opened 2015-10-02 07:13 UTC
Hello,

I just tried to go through training content. In edit.html, new.html and the corresponding controllers
company is missing. After adding the stuff almost everything is working fine. The only left problem
is, that service.deleteCustomer seems not working. 

When clicking delete in the list it jumps right to the js and the ID of entry is transferred. But the entry
still is available on home.html view. And here im stuck.

Im using 
- Visual Studio 2013 Update 5
- IE 11
- SharePoint 2013
- jquery 1.9.1
- bootstrap 3.3.5
- angularJS 1.4.6

**Comment by jthake** [comment] 2015-10-05 18:22
What module are you talking about here? Can you please specify the location of the markdown file you are referring too?

**Comment by Haystack0815** [comment] 2015-10-06 04:13
I'm talking about 
Exercise 3: Extending the AngularCRM Project with a Custom Service of https://github.com/OfficeDev/TrainingContent/blob/master/O3657/O3657-1%20Deep%20dive%20into%20building%20standalone%20AngularJS%20web%20applications%20with%20Bootstrap%20for%20Office%20365/Lab.md

The file I'm talking of is controller.js app.controller('homeController', .... and service.js service.deleteCustomer = function(id{ ...

**Comment by TBag** [comment] 2015-12-15 15:45
@jthake 

We tested with the exact same environment on a couple of different machines and cannot reproduce the issue.

**Comment by jthake** [comment] 2015-12-15 18:26
OK if it cannot be reproduced I am going to close this issue.

**Closed by jthake** 2015-12-15 18:26 UTC
Labels: bug, Microsoft Cloud Roadshow - High Priority
